# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [374]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [375]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [376]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [377]:
pd.__version__

'3.0.6'

### Step 3. Name of the max valued product

In [378]:
#Primero paso el item_price a número. Tb se puede hacer con un .to_numeric()
chipo_new = chipo.copy()  
chipo_new['item_price'] = chipo_new['item_price'].str.replace('$', '',)  #Busca dolar y pon nada
chipo_new['item_price'] = chipo_new['item_price'].astype(float)

In [379]:
chipo_new.info()  #Veo como 'item_price' y 'precio_ud' son floats, por lo que ya puedo operar con ellos

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

In [380]:
#Segundo calculo el precio por ud. Creo esta nueva columna.
chipo_new['precio_ud'] = chipo_new['item_price'] / chipo_new['quantity']

In [381]:
chipo_new.head(10)

,order_id,quantity,item_name,choice_description,item_price,precio_ud
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [382]:
#Por último busco el producto con el precio por ud más caro. De precio ud quiero el máximo y en [] me da lo que quiero sacar
producto_mas_caro = chipo_new.loc[chipo_new['precio_ud'].idxmax(), ['item_name', 'choice_description', 'item_price', 'quantity', 'precio_ud']]
print(f"El productos más caro es: \n{producto_mas_caro}")

El productos más caro es:
item_name                                              Steak Salad Bowl
choice_description    [Tomatillo Red Chili Salsa, [Black Beans, Chee...
item_price                                                        23.78
quantity                                                              2
precio_ud                                                         11.89
Name: 281, dtype: object

In [383]:
#Como hay varios productos con el precio mínimo de 11.89:
productos_caros = chipo_new[chipo_new['precio_ud'] == chipo_new['precio_ud'].max()]
print(productos_caros['item_name'].unique())

<StringArray>
['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl']
Length: 3, dtype: str

### Step 4. How many products cost more than $10.00?

In [384]:
productos_mas_10 = chipo_new[chipo_new['precio_ud'] > 10]
total_productos = productos_mas_10['item_name'].nunique()
print(f"Hay {total_productos} productos que valen más de 10$.")

Hay 25 productos que valen más de 10$.

In [385]:
chipo_new[chipo_new['precio_ud'] > 10][['item_name', 'precio_ud']]  #Lo que va dentro del [] es una lista

               item_name  precio_ud
5           Chicken Bowl      10.98
7          Steak Burrito      11.75
13          Chicken Bowl      11.25
23       Chicken Burrito      10.98
39         Barbacoa Bowl      11.75
...                  ...        ...
4610       Steak Burrito      11.75
4611      Veggie Burrito      11.25
4617       Steak Burrito      11.75
4618       Steak Burrito      11.75
4619  Chicken Salad Bowl      11.25

[1034 rows x 2 columns]

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [386]:
total_pedidos = productos_mas_10['order_id'].nunique()
print(f"Se han hecho {total_pedidos} pedidos con un productos de más de $10.")

Se han hecho 787 pedidos con un productos de más de $10.

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [387]:
#Agrupamos por pedido y sumamos la columna item_price
#Estos nos da una lista con lo que gastó cada order_id en total
totales_por_pedido = chipo_new.groupby('order_id')['item_price'].sum()
pedidos_mas_10 = (totales_por_pedido > 10).sum()
print(f"Se han hecho {pedidos_mas_10} pedidos cuyo importe total supera los $10.")

Se han hecho 1834 pedidos cuyo importe total supera los $10.

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [388]:
#Cuento los pedidos únicos en los que se da esta condición
filas_mas_10 = chipo_new[chipo_new['item_price'] > 10]
total_pedidos_mas_10_produc = filas_mas_10['order_id'].nunique()
print(f"En {total_pedidos_mas_10_produc} pedidos se pagó más de $10 por un mismo producto.")

En 863 pedidos se pagó más de $10 por un mismo producto.

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [389]:
resultado = chipo_new.drop_duplicates(subset=['item_name', 'precio_ud'])[['item_name', 'precio_ud']]
resultado

                                  item_name  precio_ud
0              Chips and Fresh Tomato Salsa       2.39
1                                      Izze       3.39
2                          Nantucket Nectar       3.39
3     Chips and Tomatillo-Green Chili Salsa       2.39
4                              Chicken Bowl       8.49
...                                     ...        ...
3989                          Chicken Salad       8.19
4235                           Chicken Bowl       8.50
4237                    Chips and Guacamole       4.25
4509                                  Chips       1.99
4510                          Barbacoa Bowl      11.49

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [390]:
resultado_2 = resultado.sort_values(by='item_name').reset_index(drop=True)
resultado_2

             item_name  precio_ud
0    6 Pack Soft Drink       6.49
1        Barbacoa Bowl      11.49
2        Barbacoa Bowl      11.48
3        Barbacoa Bowl       8.99
4        Barbacoa Bowl      11.75
..                 ...        ...
134  Veggie Salad Bowl      11.25
135  Veggie Salad Bowl       8.75
136  Veggie Soft Tacos       8.49
137  Veggie Soft Tacos      11.25
138  Veggie Soft Tacos       8.75

[139 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [391]:
#Filtrando por el nombre del producto más caro
nombre_mas_caro = chipo_new.loc[chipo_new['precio_ud'].idxmax(), 'item_name']
cantidad_f1 = chipo_new[chipo_new['item_name'] == nombre_mas_caro]['quantity'].sum()
print(f"Cantidad ordenada: {cantidad_f1}")

Cantidad ordenada: 31

In [392]:
nombre_mas_caro

'Steak Salad Bowl'

In [393]:
cantidad_f1

np.int64(31)

In [394]:
#Agrupando por producto y buscando el máximo
cantidades_por_producto = chipo_new.groupby('item_name')['quantity'].sum()
cantidad_f2 = cantidades_por_producto[nombre_mas_caro]
print(f"Cantidad ordenada: {cantidad_f2}")

Cantidad ordenada: 31

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [395]:
veggie_salad_count = len(chipo_new[chipo_new['item_name'] == "Veggie Salad Bowl"])
print(f"Se pidieron {veggie_salad_count} Veggie Salad Bowls.")

Se pidieron 18 Veggie Salad Bowls.

### Step 9. How many times did someone order more than one Canned Soda?

In [396]:
filtro_canned_soda = chipo_new[(chipo_new['item_name'] == 'Canned Soda') & (chipo_new['quantity'] > 1)]
veces_pedido = filtro_canned_soda.shape[0]   #0 para contar filas
print(f"Alguien pidió más de una Canned Soda {veces_pedido} veces.")

Alguien pidió más de una Canned Soda 20 veces.